### ISSUE TITLE
Pin labels on PSSE generators are not correct

### ISSUE THREAD

**Issue by tinrabuzin** [OpenIPSL/OpenIPSL#114]
The pins don't correspond to its labels on the PSSE generators. @dietmarw Have you maybe shuffled them?

**Comment by dietmarw** [comment]
AFAIK I only touched the PSAT icon and connector positions. Never played with the PSSE ones.

**Comment by tinrabuzin** [comment]
@dietmarw Ok, sorry for suspecting you. :P

**Comment by dietmarw** [comment]
As a tip to avoid this... remove all icon layer annotations for those connectors. The RealOutput classes get automatically mirrored to the icon layer. So making additional changes to the position to the icon layer instead to the diagram layer "breaks" the link and makes them independent copies which probably lead to the mislabels in the past.
