### ISSUE TITLE
Doubt with GGOV1 connection

### ISSUE THREAD

**Issue by maguilerac** [OpenIPSL/OpenIPSL#119]
In some references I have seen that the governor output (output of the V Limiter block) is feeding both the main governor PID controller and the Rselect block.
However, I see that what is now being connected to the Rselect is the input of the V Limiter.

Is it correct? Should _connect(rSELECT.GovernorOutput, V.u)_ be replaced with _connect(rSELECT.GovernorOutput, V.y)_?

Reference:
Fig3-5 Dynamic Models for Turbine-Governors in Power System Studies (IEEE 2013)

**Comment by MaximeBaudette** [comment]
@maguilerac You know you can add pictures to show the inconsistencies between the two.

**Comment by maguilerac** [comment]
@MaximeBaudette Done!

Pictures for comparisson:

![im01](https://cloud.githubusercontent.com/assets/25766442/25128122/caed07f0-2438-11e7-97af-9490a0a8484f.png)
![im02](https://cloud.githubusercontent.com/assets/25766442/25128128/d11f3f4e-2438-11e7-95bd-969efebf3bf7.png)

**Comment by MaximeBaudette** [comment]
@maguilerac 
I didn't find anything in the history of the model that would justify this discrepancy between the model sheet and its implementation in OpenIPSL. BTW it was @tinrabuzin who added the model to the library, maybe he has some input. 
If not I suggest you prepare some tests and check the behavior of the model, before and after the fix.

**Comment by lvanfretti** [comment]
Nobody followed up, I'm closing the issue.

**Comment by marcelofcastro** [comment]
@lvanfretti I am following up on this. I am fixing GGOV

**Comment by lvanfretti** [comment]
@marcelofcastro then assign yourself to what you are doing and make a note it the Issue.
I don't want any open issue without someone taking ownership of it. Otherwise, we are closing it and marking it with "wont fix"

**Comment by marcelofcastro** [comment]
I'm taking over this issue

**Comment by marcelofcastro** [comment]
Issue solved with PR #254
