### ISSUE TITLE
PSSE Wind Turbine (WT) package implementation

### ISSUE THREAD

**Issue by tinrabuzin** [OpenIPSL/OpenIPSL#14]
WT3 Example: Due to some parameters which are not defined, the example won't check.

**Comment by MaximeBaudette** [comment]
Shall we then rename this issue ? to PSSE WT Fix ?

**Comment by tinrabuzin** [comment]
Yes, we can do that.

**Comment by lvanfretti** [comment]
This is being taken care of by Marcelo and Manuel, will be resolved in v2.

**Comment by marcelofcastro** [comment]
@lvanfretti, let's wait for the pull requests to be merged. After that we can check if that problem was or was not solved. Isn't it better to wait?

**Comment by lvanfretti** [comment]
@marcelofcastro you can mention this issue when the day comes.
A lot of these issues were opened by people that are no longer actively working on OpenIPSL, unless there is someone to take care of the problem, I'm closing the issue. There is not point to have a bunch of open issues.
