### ISSUE TITLE
Publish OpenIPSL also on impact (and therefore modelica.org/libraries)

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#16]
Just a small reminder that as soon as you feel ready that I can add OpenIPSL also to the impact package index on impact.github.io

**Comment by MaximeBaudette** [comment]
I was discussing with @tinrabuzin and we feel that we are very close to cleaning the library from all "model check" errors. When we have that done, we will make a release of it and you can add it on impact.

**Comment by tinrabuzin** [comment]
@MaximeBaudette @dietmarw I think the library can now be included on impact?

**Comment by MaximeBaudette** [comment]
Yes ! I'll prepare it!

**Comment by MaximeBaudette** [comment]
@tinrabuzin now I remember why I haven't done it so far...
I needed to implement the updated copyright notice. Now that OM have corrected the bug named in #47 I will be able to take care of that! 
Once the copyright is updated, I will also save the library once again in Dymola to fix the formatting and update the version number, and prepare a new release. 
Then @dietmarw can add it to Impact!

**Comment by MaximeBaudette** [comment]
@dietmarw 
Now we are ready to include OpenIPSL to Impact. I will create the version v1.0.0 before the end of the week.

**Comment by MaximeBaudette** [comment]
Ping @dietmarw 
I tried searching on impact.github.io but didn't find the library. Any thing we still need to fix?

**Comment by dietmarw** [comment]
Well actually creating a v1.0.0 release perhaps? ;-)

**Comment by MaximeBaudette** [comment]
I thought I did it:
https://github.com/SmarTS-Lab/OpenIPSL/releases/tag/v1.0.0
What did I do wrong then :cry: ?

**Comment by dietmarw** [comment]
My bad, I overlooked that one since the title sad nothing wit a version number. There is a different issue now coming up which currently is preventing OpenIPSL from not showing up in the impact index. Nothing you can/have to worry about. I'm on it.

**Comment by MaximeBaudette** [comment]
Great News! 
Please let me know if there is more I need to do or if I can close the issue.

**Comment by dietmarw** [comment]
Leave it open for now so I can close it once I fixed the impact issue.

**Comment by dietmarw** [comment]
OpenIPSL is listed on modelica.org/libraries. For technical reasons it will not appear on the impact index. The impact index might undergo a substantial redesign which will most likely also fix the listing of OpenIPSL. So closing this isssue now.
