### ISSUE TITLE
PSAT AVR models mixed up.

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#164]
When working with the AVR models from the PSAT package we noticed the following:

`OpenIPSL.Electrical.Controls.PSAT.AVR.AVRTypeI` 
and 
`OpenIPSL.Electrical.Controls.PSAT.AVR.AVRTypeII`

are actually swapped. So `AVRTypeI`should be `AVRTypeII` and vice versa. Now the real tricky bit is here that also PSAT got this wrong. If you look at the official IEEE definitions and literature (e.g., M. Federico, Power-System-Modelling-and-Scripting. New York: Springer Science & Business Media, 2010.) you'll see that the PSAT manual got it wrong and hence OpenIPSL "copied" this. 

So rather than having the identical (wrong) naming from PSAT I'd suggest to swap the models around and document this in-consistency with regards to PSAT. Of course this will have an impact on user models. Question is if it will not even fix user-models since they were not aware that they did not use the proper AVR type.

**Comment by MaximeBaudette** [comment]
@dietmarw 
My first reaction to your post is that, given that our user community is not that big, it's not such a big deal if we swap the names to fix it w.r.t the standard.

**Comment by dietmarw** [comment]
We could actually solve this with a conversion script so that user-models get updated. But this change being non-backwards compatible would mean that the semantic version of the next release should be 2.0.0. Maybe there are some other more major changes that are planned and should be bundled with such a release. Not sure what your release plan looks like for OpenIPSL.

**Comment by MaximeBaudette** [comment]
I don't think we have a very defined plan at the moment, and for my part, I'm pretty busy these days, so I don't spend too much time on OpenIPSL. But I think @lvanfretti is getting new students who are gonna work on the library very soon! Hopefully the second half of 2018 will see a more busy repository :-)

**Comment by lvanfretti** [comment]
@MaximeBaudette this is something that we have to put in the to-do list for @marcelofcastro who will take over your admin and main dev role.
@dietmarw I like the idea of the script, Marcelo starts in the end of August, let's follow up then and talk about future releases. For the time being, I guess this could be "patched" manually.

**Comment by marcelofcastro** [comment]
Guys, was this issue solved? Did we changed the names?

**Comment by dietmarw** [comment]
I need to check. Probably will manage that next week.

**Comment by dietmarw** [comment]
I had a look this morning. So nothing was changed for now. The thing really is to decide how the PSAT models should be used. Given the name the idea is probably to be able to recreate PSAT examples using OpenIPSL. In that case it would be unfortunate that the AVR types are different wrt PSAT even though more correct wrt the original IEEE source. 
So my suggestion is to maybe simply document inside these two models and pointing out the issue. I'd even go so far to add a small message in red on the diagram level.

**Comment by lvanfretti** [comment]
This is a good approach, the original intent was to clone PSAT models and examples for dynamic studies.
