### ISSUE TITLE
Add a HYGOV model

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#168]
The standard hydro power turbine governor of type `HYGOV` would be a useful addition.

**Comment by lvanfretti** [comment]
@dietmarw it is already available:
[./Electrical/Controls/PSSE/TG/HYGOV.mo](https://github.com/OpenIPSL/OpenIPSL/blob/master/OpenIPSL/Electrical/Controls/PSSE/TG/HYGOV.mo)

**Comment by dietmarw** [comment]
Ah sorry ... didn't see that.
