### ISSUE TITLE
PwShunt causes division by zero

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#174]
When using `Electrical.Banks.PwShunt` Dymola (at least) displays 
``` 
Model error - division by zero: (1.0) / (pwShunt.p.ir^2+pwShunt.p.ii^2) = (1) / (0)
```
but in the end succeeds.
This should be investigated.

**Comment by dgusain1** [comment]
I have similar problems. But in my case, the simulation does not go through. Im using the Two area system from Application Examples.

**Comment by marcelofcastro** [comment]
This problem occurs also when using `Electrical.Banks.PwShuntC` and `Electrical.Banks.PwShuntR` and it occurs during the initialization. When the variable is an iteration variable of the initialization problem and no start value is given, 0 is used and this is what is causing the problem. Some non-linear solvers in Dymola are able to deal with the problem (as it is shown below) but I don't know about other solvers and other software tools. @dgusain1 are you using Dymola? If yes, try to change the solver to _dassl_.

'Non-linear solver will attempt to handle this problem.'

One solution is to define an initial guess for the imaginary and real parts of the current, that is not zero. For instance, we can initialize these values with Modelica.Constants.eps, which is defined as:

> Biggest number such that 1.0 + eps = 1.0

Hence, the code written below would solve the error/warning.
`OpenIPSL.Interfaces.PwPin p(
ir(start=Modelica.Constants.eps), ii(start=Modelica.Constants.eps)
)` 

@dietmarw do you have a better solution for this?

**Comment by dietmarw** [comment]
That looks like a good solution. Actually I'm going one step further and defining the non-zero start value (only a guess value after all) for `OpenIPSL.Interfaces.PwPin.ir|ii` itself. I don't think that will cause any problems and will on the contrary solve also other example models. PR is coming up.

**Comment by marcelofcastro** [comment]
@dietmarw That means that this issue was solved, right?
