### ISSUE TITLE
Include PSAT PSS and load models from FOSSEE1 branch

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#186]
In order to check some boxes in #81 the FOSSEE1 branch provides the following models that could be merged(target location):

 - Examples.Loads.PSAT.ThermostatLoad
 - Examples.Loads.PSAT.BaseClasses.LoadBase (and adapt the other existing load tests for this)
 - Electrical.Loads.PSAT.ThermostatLoad
 - Electrical.Controls.PSAT.PSS.PSSTypeI 
 - Electrical.Controls.PSAT.PSS.PSSTypeIII

The OEL models are duplicates of the existing models.

The only thing left (despite the rearranging of course) is adding some documentation to the models and also having an example each for the PSS models.

@BiswarupM Do you still have the possibility to contribute here?

**Comment by dietmarw** [comment]
@Biswarup I was wondering if you could simply add some short documentation to the models. I can then take care of adding them to the OpenIPSL library itself.

**Comment by dietmarw** [comment]
Never mind @BiswarupM. I've added some references to the models in #232.

**Comment by BiswarupM** [comment]
No problem @Dietmar. I just saw it.
Thanks!
