### ISSUE TITLE
Application Examples and Library have mixed notations

### ISSUE THREAD

**Issue by dgusain1** [OpenIPSL/OpenIPSL#188]
The latest version of OpenIPSL library has changed voltage notations for loads (as far as I have checked) to v_0, while the application examples still use V_0. This causes translation errors.

**Comment by dietmarw** [comment]
Hi, if you mean with latest version the `master` branch which is in development then yes. This is something we are aware of. Latest stable version is still https://github.com/OpenIPSL/OpenIPSL/releases/tag/v1.5.0

Could you confirm and close if this issue is regarding the (unstable) master branch?
