### ISSUE TITLE
Remove SMIBpartial2 and instead update SMIBpartial

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#221]
The new base model for examples `OpenIPSL.Examples.SMIBpartial2` is probably not necessary. Instead I suggest to update the existing `SMIBpartial` model with the changes done in `SMIBpartial2`. The additional shunt and the split of the power line should not have an impact on any of the examples.

**Comment by marcelofcastro** [comment]
This is true. The `SMIBpartial2` can supersede `SMIBpartial`. As you said the additional shunt and would not cause any problem in the simulation of the other models.

**Comment by dietmarw** [comment]
OK in that case I can create a PR where I also clean up the SIMBpartial at the same time. Because it currently does look rather ugly.
