### ISSUE TITLE
Rename STB5B to ESST5B

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#223]
When working on #222 I noticed that there exist an example and model for `ST5B` which probably should be called `ESSTB5` just like the 1A and 4B variant. 
I can create a PR if that is fine.

**Comment by marcelofcastro** [comment]
@dietmarw there is no `ESST5B` in PSS/E. The correct name for the standard model is `ST5B.` It is quite silly, but I guess it is better to maintain the PSS/E naming for easy correspondence. Therefore, I believe we should keep the name `ST5B`.

**Comment by marcelofcastro** [comment]
If you agree with that, we can close this issue.

**Comment by dietmarw** [comment]
Yes in that case it makes sense to keep it as is.
