### ISSUE TITLE
GGOV1 needs to get cleaned up.

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#226]
`Electrical.Controls.PSSE.TG.GGOV1.GGOV1` needs to be moved one level up and the support models for that block put under `BaseClasses`.  At the same time the documentation needs to get fixed for the support models.

**Comment by dietmarw** [comment]
Also good to look at #119 at the same time.

**Comment by lvanfretti** [comment]
@dietmarw other than the issue in #119 on the connection, another thing that Miguel did was to look at the diagram and try to reorganize the whole mess into logical pieces, i.e. what each part of the diagram represents, and then separate it in blocks. The final version of that model is in this repo: [link](https://github.com/ALSETLab/2018_AmericanModelicaConf_PowerGrid_plus_PowerSystems).

**Comment by lvanfretti** [comment]
@marcelofcastro this would be a good assignment for Fernando so he learns the workflow of cleaning up things with you. Can you discuss with him and have him help @dietmarw ?

**Comment by marcelofcastro** [comment]
Issue solved with PR #254
