### ISSUE TITLE
Version 2.0.0 Release

### ISSUE THREAD

**Issue by marcelofcastro** [OpenIPSL/OpenIPSL#247]
### Issues to solve for 2.0.0 release:

- [x] #250  
- [x] #246 
- [x] #226 
- [x] #179 
- [x] #165 
- [x] #162 
- [x] #160 
- [x] #119 
- [x] #112 
- [x] #67 
- [x] #219
- [x] #255 
- [x] Mirror the info of the packages structure in the OpenIPSL landing info layer. 
- [x] #287
- [x] #277 
- [x] #173 
- [x] General clean-up before release, like description sentence in packages and verification of documentation display.
- [x] Clean up the whole library with ttws

**Comment by lvanfretti** [comment]
@dietmarw @marcelofcastro can we add: 
- modify/update the readme.md. We need to synthesize and move materials that are not needed in the landing markdown to others. I think it would be great if it could look like other Github repositories, and move other things accordingly.
- add funding information. @marcelofcastro we need to add the support of NYPA/NYSERDA and CURENT, I need to add OpenCPS support during a year or so, and @dietmarw should add anything that is supporting him to contribute to this effort.

**Comment by dietmarw** [comment]
> and @dietmarw should add anything that is supporting him to contribute to this effort.

OK I'll try to include a personal paypal donate button then. :-D
