### ISSUE TITLE
Automatic Validation with Travis CI

### ISSUE THREAD

**Issue by MaximeBaudette** [OpenIPSL/OpenIPSL#26]
Issue to discuss creating a framework for adding the possibility of automatic validation of the model by the CI server.

**Comment by MaximeBaudette** [comment]
Some of the components are failing cause of a problem in OM with replaceable components:
https://trac.openmodelica.org/OpenModelica/ticket/2079

**Comment by MaximeBaudette** [comment]
Current implementation of the CI does NOT produce an error when the library fails to load

**Comment by tinrabuzin** [comment]
@MaximeBaudette I think we fixed this problem with replaceable components? I don't remember how anymore...

**Comment by lvanfretti** [comment]
Being replaced with new CI by Marcelo and Manuel in the next release.

**Comment by marcelofcastro** [comment]
> Being replaced with new CI by Marcelo and Manuel in the next release.

@lvanfretti I think the CI will be replaced in v2.0 not v1.9...

**Comment by lvanfretti** [comment]
@marcelofcastro fine, but still, it won't be related to this issue.
Nobody is taking care of it, and it will be replaced, so I'm closing this.
