### ISSUE TITLE
Bus

### ISSUE THREAD

**Issue by zvalasksa** [OpenIPSL/OpenIPSL#276]
I start learning Modelica, can someone tell me how i can change the component form for example the Bus and line 
when i draw a Bus or Line is having a Square Form

**Comment by lvanfretti** [comment]
If you want to edit the graphical appearance, you need to resize the object on the graphical view or alternatively modify the model/class you are instantiating within its Icon layer.
Please note, this is not a forum to ask generic Modelica questions, the Issues tab should only be used to report bugs or similar related to OpenIPSL. Please ask generic Modelica questions somewhere else, if you are using OpenModelica, go here: https://openmodelica.org/forum
