### ISSUE TITLE
GGOV1 variant for linearization or update using Pade model

### ISSUE THREAD

**Issue by lvanfretti** [OpenIPSL/OpenIPSL#277]
@ManuelNvro and @dietmarw 

@sergio-dorado reported an issue over email that I will add below.

When attempting to linearize certain blocks (e.g. the delay=`Modelica.Blocks.Nonlinear.FixedDelay` model), any Modelica tool should fail.  This is expected when using that model as it is not possible to linearize it, it does not use either functions for derivatives or a smooth operator-based implementation.

Most user's of this library will not understand this, and think there is a problem with the tool or the library.

We have two choices, 

1. either create model variants that are "fit for linearization" that can be easily replaced, 
2. or that we replace all "delay" blocks with a Pade approximation from (`Modelica.Blocks.Nonlinar.PadeDelay`) 

@marcelofcastro if we replace with the Pade approximation we have to run all the CI tests to made sure we have the new results for all models that have the change...

My preference would be for no. 2, because I don't think the user's will pay attention to the availability of a variant, but that of course gives more work in running CI tests.
What do you think @marcelofcastro and @dietmarw?

Issue report from @sergio-dorado (please do this using the Issues tab next time!):

> ---------- Forwarded message ----------
> From: Sergio A. Dorado-Rojas <sergio.dorado.rojas@gmail.com>
> Date: Jul 31, 2021, 7:53 AM -0400
> To: Marcelo de Castro Fernandes <decasm3@rpi.edu>, Giuseppe Laera <laerag@rpi.edu>
> Cc: Luigi Vanfretti <luigi.vanfretti@gmail.com>
> Subject: Issues with Delay Block for Linearization
> 
> Hi all,
> 
> I have been working with an OpenIPSL model for my internship. I was trying to perform a linear analysis to change some AVR’s parameters and found something that I think is worth to discuss.  The model has a single generator with TG (GGOV1) and ES (ESST4B). Marcelo did the translation for me so it is working on the latest OpenIPSL version. I did not create this as an issue on GitHub because ... **redacted.**

![Attachment-2](https://user-images.githubusercontent.com/7248948/127748959-7fcf3b3f-3239-48c9-a3fb-bba85f4a1a6f.png)
> 
> Whenever I try to use any function within the Linear Analysis menu, I get this message. The linear analysis is not carried out.
> 
![Attachment](https://user-images.githubusercontent.com/7248948/127748968-9bedb47a-642f-4231-bd34-8e54af1c4d4d.png)
> 
> 
> So, I traced down the model for delay blocks and found that there is one in the turbine model. 
> 
![Attachment-2](https://user-images.githubusercontent.com/7248948/127749647-bc629f4f-3cf0-414e-a956-5e2f110e27f4.png)

> 
> 
> For my particular case, the delay time was exactly zero so I removed the block. The linear analysis functions could be used perfectly afterwards.
> 
> In my humble opinion, it doesn’t speak highly for the library that the linear functions cannot be used for such blocks. I’d suggest to replace the linear block by a Padé approximation. However, I don’t know much of how this would impact the exactitude of the model against its PSS/E counterpart. I haven’t tried this workaround myself since I am not familiar at all with this particular exciter’s structure and, as I mentioned above, for my immediate needs it was better to remove the block. 
> 
> Let me know what your thoughts are. 
> 
> Best,
> Sergio

**Comment by marcelofcastro** [comment]
couldn't we just set the environment variable, as suggested by the log? I guess that replacing the delay block, which is supposed to be the correct way of doing it, by a Pade approximation, for example, would be just constraining a model of its full behavior just for the sake of linearization. It doesn't seem wise to me to fully modify the block. In addition, if we can just set the environment variable for the linearization and continue with the block the way it is right now might be the easiest solution. That said, if we really want to address the issue by changing the turbine representation, I guess we can use a block that can be replaced by Delay or PadeApprox depending on a "choice" parameter, where the user can select what they want: the correct implementation or the Pade block. @dietmarw what's on your mind?

**Comment by lvanfretti** [comment]
I agree with using the choice and allowing to select between models, that seems to be the best way forward.

Luigi

**Comment by dietmarw** [comment]
I agree with @marcelofcastro that we really should not restrict the dynamic models for the sake of linearisation which kind of defeats the powers of the dynamic simulations possible in Modelica. So if one wants to linearise it for a certain application then this should happen by using the suggested env variable offered by the tool and not changing the model implementation itself.

**Comment by lvanfretti** [comment]
Marcelo and Dietmar

I did a bit more digging, I created a simple model to reproduce the error.
Dymola’s developer has confirmed the way of setting the flag.

Now, you can see from his response below that when using the flag the delay is approximated assuming a very large time horizon and suggests that we use a Pade approximation.

So, I think we should have a “choice” for the models at the top level where we have the delay part as a replaceable model and it can use the Pade for cases like this.

Best

Luigi



From: OLSSON Hans ***@***.***>
Date: Aug 13, 2021, 3:44 AM -0400
Subject: RE: How to set DYN_ENABLE_DELAY_LIN and related documentations
> Hi Luigi, To set flag:Modelica.Utilities.System.setEnvironmentVariable("DYN_ENABLE_DELAY_LIN", "1");before running linearize.To unset just replace the "1" by "".We don’t have direct support for setting this when opening the library.Without the flag you get an error message, and no result.With the flag set it is as if delay(x,t)=x – i.e. the approximation when considering a very long time horizon.I would say that replacing the delay by PADE-approximation is the correct choice if you want really good results for appropriate times. Best Regards,
> Hans OLSSON
> Modelica Multi-Physics/Control Software Engineering Senior Specialist
>
> 3DS.COM/CATIA
> Dassault Systemes AB | IDEON Gateway, Scheelevägen 27 | SE22363 Lund | Sweden
>  From: Luigi Vanfretti ***@***.***>Sent: Friday, August 13, 2021 01:12Subject: How to set DYN_ENABLE_DELAY_LIN and related documentations
>
> EXTERNAL EMAIL :  The sender of this email is external to 3DS. Be wary of the content and do not open unexpected attachments or links. If you consider this email as spam, you can click here (no login or additional action will be requested).
>  Hello! When linearizing a model we got the following message:More details about the specific case are found here:https://github.com/OpenIPSL/OpenIPSL/issues/277Naturally, replacing it with a Pade block does the trick and the model can be linearized. Since I do not have the model from the post above, I created a simple example to reproduce the error, which is also attached: I am very intrigued with the message:A model using delay is linearized; the results would not be correct.If you really want to get some results you can set the environment variable, DYN_ENABLE_DELAY_LIN, please contact support for more information.
> I searched in the manual and online to figure out how to set this environment variable with no luck. However, after setting the variable to 1, I was able to linearize the model:Modelica_LinearSystems2.ModelAnalysis.Linearize("FixedDelayError"); ss.A =            x1 ss.B =                        u1 ss.C =            x1                     y1 ss.D =                        u1                     y1  0.9999999   When using the other option for linearization, I get the following:linearizeModel("FixedDelayError", stopTime=0); = trueWith the results in dslin.mat being: So, it seems like this is the correct way to set the flag. Now, the reason for this email is that I want to figure out what is happening.I would like to understand: •  how to set the flag (if possible, could it be set through a .mos script or when loading a library?),  • what Dymola will do when the flag is enabled vs when it is not enabled?,  • how and when to use it to get acceptable results.Since there is no documentation, I was hoping you could help giving me some internal documents. Thanks a lot for any insight. Luigi

**Comment by dietmarw** [comment]
I've checked and the `FixedDelay` is used only in:
- `OpenIPSL.Electrical.Controls.PSSE.TG.BaseClasses.GGOV1.Turbine`
- `OpenIPSL.Electrical.Solar.KTH.PFblocks.MPPT`
The latter is probably not even present any more after merge of #267 
So I think it is overkill to add a global parameter just to trigger **one** change in **one** model. Instead what I suggest we can do is to make the `delay` block replaceable and constrain the replacement choice to `PadeDelay`. That way one can make the change in the model for linearisation if it is needed.

**Comment by lvanfretti** [comment]
Sounds like a great approach.
We should also add default parameters for the delay, let me look that up when I get to the office.

**Comment by dietmarw** [comment]
@lvanfretti I've just created a fix for this and all that is missing now is some nice defaults which we can add as documentation in the info layer. Did you manage to get to your office in the mean time ;-)

**Comment by lvanfretti** [comment]
@dietmarw working from home today buddy! I'll go an approve that fix, thank you!

**Comment by dietmarw** [comment]
Yes, make a new ticket for 3.1.0 (for now). The selection of models can be done via parameter (already done in `OpenIPSL.Electrical.Machines.PSSE.Plant`) but question is how often will this be needed? Anyway, have a new ticket and continue the discussion there.

**Comment by dietmarw** [comment]
Actually! It is a VERY simple fix by adding "choicesAllMatching=true"

**Comment by lvanfretti** [comment]
I tried that but was not behaving how I was expecting it to if you see the removed commented text in [fea08e4](https://github.com/OpenIPSL/OpenIPSL/pull/288/commits/fea08e4bca3d71822ff956933044d33889dae9d1), maybe you have better luck? I'll open the other issue anyway.
