### ISSUE TITLE
GGOV1 - Enhancements - Enable variants for linearization from the top layer

### ISSUE THREAD

**Issue by lvanfretti** [OpenIPSL/OpenIPSL#289]
Follow-up from #277, this issue is to document a potential enhancement, for user friendliness to implement in future releases.

- [x] Provide means to select which model to replace by, i.e. select between Pade or Fixe, from upper level (GGOV1) layer, through some means. Via parameter (?).
- [x]  Create test model for Pade variant.
- [ ] Create application case. This should be an example to show how to compare model variants in time-simulation, compare linearized vs non-linear variant model responses.  

The last item is more as an excuse of showing potential problems of linearization when sub-components are non-linearizable, hence, improving this model can help provide a guideline on creating model variants for any other sub-components needed in models that require a differentiable variant.

**Comment by lvanfretti** [comment]
See: 
- https://github.com/OpenIPSL/OpenIPSL/issues/277#issuecomment-1124972847 and
- https://github.com/OpenIPSL/OpenIPSL/issues/277#issuecomment-1124975699
For future discussion.

**Comment by dietmarw** [comment]
I've started #290 which now adds (in Dymola) the following dialogue: 
![image](https://user-images.githubusercontent.com/9332/168085479-deade6b0-156f-4e00-b8ed-c36e7130f67d.png)

**Comment by dietmarw** [comment]
I forgot to propagate the choice also upwards into the `GGOV1` and `GGOV1DU` models. That's done now.

**Comment by lvanfretti** [comment]
@dietmarw see testing issue on https://github.com/OpenIPSL/OpenIPSL/pull/290#issuecomment-1125071324

**Comment by dietmarw** [comment]
I think we should create a new issue for 
"
 Create application case. This should be an example to show how to compare model variants in time-simulation, compare linearized vs non-linear variant model responses.
"
What do you think @marcelofcastro

**Comment by marcelofcastro** [comment]
I think it's a good idea to do that, @dietmarw. So we can set the 3.1.0 milestone to that issue, right?

**Comment by dietmarw** [comment]
Yes, exactly. And close this issue here.

**Comment by marcelofcastro** [comment]
Sounds good!

**Comment by marcelofcastro** [comment]
The last task here is now tracked in issue #292 and I am closing this one.
