### ISSUE TITLE
'abs' function not properly converted to MSL 4.0.0

### ISSUE THREAD

**Issue by GiuseppeLaera** [OpenIPSL/OpenIPSL#301]
When I checked the GENROU model from OpenIPSL ver. 3.0.0 with Dymola 2023 I got the following error message:
![image](https://user-images.githubusercontent.com/15262466/174908874-28ee4576-b5e0-4782-8236-e7cb0ada1abf.png)
Trying to fix the error I added the following line importing the "abs" function:
`import Modelica.ComplexMath.abs;`
and the function "abs" has been used in the model without single quotation marks.
We need to check the other models as well where "abs" is being used.

**Comment by dietmarw** [comment]
Nice catch. I prepared #302 to fixe this. We now need to decide if we want to create a 3.0.1 bug fix release for this.
