### ISSUE TITLE
SystemModeler v13.0, v13.1 issues

### ISSUE THREAD

**Issue by lvanfretti** [OpenIPSL/OpenIPSL#307]
There are some issues with the latest version of WSM, this is the email sent to WSM development team:

Hello WSM Friends,

We have recently released a new version of our library (V3.0.1) supporting MSL 4.0.0.

Just when I thought we didn't have any compatibility issues with WSM, we got a nasty bug popping up that was reported to me by one of your industrial users, Mr. Glen in cc.
![image](https://user-images.githubusercontent.com/7248948/184654041-f5537233-0373-4e60-9d47-d3650f3aabc1.png)
![image](https://user-images.githubusercontent.com/7248948/184654069-dd9b35e9-dd7f-41a2-adef-6ee6494bcbc5.png)

I've submitted a ticket with the text below via this link:
https://www.wolfram.com/support/contact/?topic=technical

This was an unfortunate surprise, not showing up in OpenModelica or Dymola, we'll try Modelica Impact to see if it pops up there, but kind of looks like a weird bug on your side when I inspect the logs from OM and Dymola... 

We want to submit a user presentation to your conference this year, so it would be really nice if you can help us kill the bug so that Mr. Glen can do more of his testing on the model translation tool his developing together with us, which you can read about here:
https://alsetlab.github.io/NYPAModelTransformation/

Thanks

Luigi

*** Text send via ticket:

Hello,
We have an issue with SystemModeler with one of our Modelica models that appears a SystemModeler issue as it does not appear in two other Modelica tools (Dymola 2022x and OpenModelica 1.19.0):

Building "OpenIPSL.Examples.IEEE14.IEEE_14_Buses" as experiment "IEEE_14_Buses 1" started at 11:54:36
Error: OpenIPSL.Electrical.Controls.PSAT.AVR.AVRTypeII [34:3-34:3] Incompatible variability. groupBus1_1.AVR1.vf0 is discrete-time but the expected variability is parametric.
Build finished at 11:54:39 (took 00:02).

To reproduce the error :
- Download this release of OpenIPSL: https://github.com/OpenIPSL/OpenIPSL/releases/tag/v3.0.1
- Open SystemModeler
- Right click on the Modelica Standard Library , in the context menu, go to version and select 4.0.0.
- Open OpenIPSL
- Open the following model: OpenIPSL.Examples.IEEE14.IEEE_14_Buses
- Click on Simulate class

Can you please address this bug?

**Comment by lvanfretti** [comment]
Response from  WSM team:

Hi Luigi,

Sorry for the slow response, I have been out of the office until today.

The response from one of the developers on this issue:

This is a known issue in the Modelica Specification. We tried to make it change but it is taking time:
https://github.com/modelica/ModelicaSpecification/issues/2602

Since the opinion of the community seems to be in favor of relaxing the check, we will do so for next release (the one after 13.1).


In the meantime, the strict checking can be deactivated to bypass this message (together with many other checks):

    * Navigate to Tools -> Option -> Global -> Translation

    * Untick "Strict Modelica compliance checking"



Thanks,
Malte

**Comment by lvanfretti** [comment]
Follow up tests done by @gkhalley:

The Build finished for the following system:
Open IPSL 3.1.0-dev
IEEE_9_Buses example
WSM 13.1
Modelica 4.0.0
![image](https://user-images.githubusercontent.com/7248948/184654760-17940f34-1254-47ad-8c3e-f8d54aeb2777.png)
From the Simulation Center:

```
Starting simulation of experiment "IEEE_9_Buses 1" at 10:43:55
[GENERAL   ] Server listening on [127.0.0.1:52587](http://127.0.0.1:52587/)
Warning: [NONLIN_SYS] Accepting solution to nonlinear system with root mean square residual 1.23949e-14, even though nonlinear solver gave up due to lack of good progress. [77»] [@0.0 s]
Warning: [NONLIN_SYS] Accepting solution to nonlinear system with root mean square residual 2.1269e-34, even though nonlinear solver gave up due to lack of good progress. [14»] [@0.0 s]
[GENERAL   ] Initialization finished.
Warning: [NONLIN_SYS] Accepting solution to nonlinear system with root mean square residual 7.41008e-33, even though nonlinear solver gave up due to lack of good progress. [14»] [@13.73E-9 s]
Warning: [NONLIN_SYS] Accepting solution to nonlinear system with root mean square residual 1.17429e-30, even though nonlinear solver gave up due to lack of good progress. [14»] [@13.73E-9 s]
Warning: [NONLIN_SYS] Reached limit of 3 warnings about lack of good progress. No more warnings will be reported for this system. [14»] [@13.73E-9 s]
Warning: [NONLIN_SYS] Accepting solution to nonlinear system with root mean square residual 2.01949e-16, even though nonlinear solver gave up due to lack of good progress. [6»] [@3.00000000 s]
Warning: [NONLIN_SYS] Accepting solution to nonlinear system with root mean square residual 2.35278e-16, even though nonlinear solver gave up due to lack of good progress. [6»] [@3.00000001 s]
Warning: [NONLIN_SYS] Accepting solution to nonlinear system with root mean square residual 2.96905e-16, even though nonlinear solver gave up due to lack of good progress. [6»] [@3.00000017 s]
Warning: [NONLIN_SYS] Reached limit of 3 warnings about lack of good progress. No more warnings will be reported for this system. [6»] [@3.00000017 s]
[GENERAL   ] Simulation stopped. [@20.00000000 s]
[GENERAL   ] Integration took 35.530000 seconds.
[GENERAL   ] Total number of function evaluations: 107361
[GENERAL   ] Total number of events: 156
[GENERAL   ] Total number of step events (dynamic state switches): 0
Simulation exited at 10:44:31
```

Glen

**Comment by lvanfretti** [comment]
New email sent to WSM to address issue:

Hi Malte,

As you can see below, my colleague, Glen, was able to run tests with version 13.1 and we are having some major problems with initialization.
Do you have a newer version of WSM in beta that we can test?

After discussing it with Glenn, we concluded that it must be an issue with version 13, since he also did not find any of these issues with version 12.3.

We submitted a presentation for your conference, and Glenn will be there to present it.
We wanted to try to sort this problems before your conference, so Glen can use the latest version of your tool and our library.

Best

Luigi

**Comment by lvanfretti** [comment]
As of 08/15/2022 - Luigi working on getting access to beta version of WSM 13.2 for testing if issue still appears.

**Comment by dietmarw** [comment]
@lvanfretti Can this be closed?

**Comment by lvanfretti** [comment]
@dietmarw yes because #308 was addressed, and according to the WSM team (not sure if it was @maltelenz) it should take care of this issue.
