### ISSUE TITLE
Invalid relations on reals

### ISSUE THREAD

**Issue by maltelenz** [OpenIPSL/OpenIPSL#308]
There are multiple occurrences of relations used on Real, which are invalid according to the Modelica specification. Here are the first few cases I found:

https://github.com/OpenIPSL/OpenIPSL/blob/f02576fcbf70ac28039bda2a463b71b002150f73/OpenIPSL/Electrical/Branches/PSAT/TwoWindingTransformer.mo#L44

https://github.com/OpenIPSL/OpenIPSL/blob/f02576fcbf70ac28039bda2a463b71b002150f73/OpenIPSL/Electrical/Controls/PSSE/PSS/IEEEST.mo#L64-L68

https://github.com/OpenIPSL/OpenIPSL/blob/f02576fcbf70ac28039bda2a463b71b002150f73/OpenIPSL/Electrical/Machines/PSAT/Order4.mo#L25

**Comment by lvanfretti** [comment]
Thanks @maltelenz, some of these have been taken care in https://github.com/OpenIPSL/OpenIPSL/pull/265 but not yet in main branch, @marcelofcastro will take a look at it after August 31st.

**Comment by tbeu** [comment]
See #310.
