### ISSUE TITLE
Cyclical dependency on function input

### ISSUE THREAD

**Issue by maltelenz** [OpenIPSL/OpenIPSL#316]
The function input `K_C` in `OpenIPSL.Electrical.Controls.PSSE.ES.BaseClasses.invFEX` has a cyclical dependency:

```
Error: OpenIPSL.Electrical.Controls.PSSE.ES.BaseClasses.invFEX Invalid declaration equation. Cyclical dependency involving: K_C.
```

**Comment by lvanfretti** [comment]
Thanks @maltelenz! Hopefully @marcelofcastro can take a look at this soon.

**Comment by dietmarw** [comment]
@maltelenz  #333 should take care of this.
