### ISSUE TITLE
Cyclical dependency in input

### ISSUE THREAD

**Issue by maltelenz** [OpenIPSL/OpenIPSL#358]
This:

https://github.com/OpenIPSL/OpenIPSL/blob/1d2236d778d20d5115fe83fdd52dbffbc3a7183e/OpenIPSL/Electrical/Controls/PSSE/ES/BaseClasses/invFEX.mo#L3

has a problem with cycles (reported by Wolfram System Modeler):

> Error: OpenIPSL.Electrical.Controls.PSSE.ES.BaseClasses.invFEX [2:3-2:3] Invalid declaration equation. Cyclical dependency involving: K_C.

**Comment by dietmarw** [comment]
Thanks, it looks like the merge of a PR accidentally reintroduced this problem again. It is now fixed (again).
