### ISSUE TITLE
OpenIPSL testing in OpenModelica

### ISSUE THREAD

**Issue by MaximeBaudette** [OpenIPSL/OpenIPSL#88]
The OpenModelica developers included the library in their testing suite:
http://libraries.openmodelica.org/branches/master/OpenIPSL/OpenIPSL.html

The testing suite uses the experiment annotations to simulate the models, which has problems with our current implementation using a partial model (power grid), with experiment annotations that are inherited by all other models. 
The OM testing suite does not deal well with the inherited annotations. The proposition is to move these annotations into each example models.

**Comment by lvanfretti** [comment]
This is no longer relevant, new test suite being developed by Marcelo and Manuel.
