### ISSUE TITLE
New dynamic power display

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#92]
I've created a new way of the power line display and wanted to get some feedback if this is fine for you.

I got rid of the arrows and replaced it with indicators instead. Also there won't be any negative values in the display but just flipping direction indicators.

Here is how it looks like in action. Left the new way I like to implement and to the right the old way:

![powerline](https://cloud.githubusercontent.com/assets/9332/23253867/41bbaca4-f9b6-11e6-9143-ff1796c1f274.gif)

**Comment by MaximeBaudette** [comment]
It looks very good!

**Comment by tinrabuzin** [comment]
@dietmarw I like it! :)

**Comment by dietmarw** [comment]
OK in that case I'll continue with this. I leave this ticket open until the actual PR is merged.

**Comment by dietmarw** [comment]
I've implemented it as par of #91

**Comment by dietmarw** [comment]
Here the next improved generation that also allows flipping:
![powerlinenew](https://cloud.githubusercontent.com/assets/9332/23303370/09bb7440-fa94-11e6-8a9e-cd8094741ceb.gif)

**Comment by dietmarw** [comment]
Should have been closed long time ago.
