### ISSUE TITLE
Generator Interface and Plant Model

### ISSUE THREAD

**Issue by tinrabuzin** [OpenIPSL/OpenIPSL#97]
I just noticed that now we have a generator model in the `Interfaces` package. I started thinking about the plant model where you could select different parts of the plant model from a dropdown menu to avoid connections and a mess that comes with that. So, @dietmarw I'd like your opinion on the implementation. Do you think what I did makes sense? You can find the plant model in the "PlantModel" branch under `Electrical.Machines.PSSE`.

**Comment by dietmarw** [comment]
Sorry but I can't find **any** model called `PlantModel`

**Comment by tinrabuzin** [comment]
That's because the name of the model is `Plant` and not `PlantModel`. :) Sorry.

**Comment by tinrabuzin** [comment]
Also, if you go to GENSAL example you can see how it would work. In Dymola at least...

**Comment by tinrabuzin** [comment]
And yes, as I wrote in the first post, the model is in the "PlantModel" branch.

**Comment by dietmarw** [comment]
OK now I see. Sure that's nice but since it is not yet supported in OMEdit, i would propably be careful as to how to introduce this.

**Comment by dietmarw** [comment]
PR #157 implements the new structure without relying on replaceable support. I.e., there is an example "GEN" that demonstrates the use but the existing models are not touched so they stay usable with OMEdit.

**Comment by dietmarw** [comment]
This was fixed as part of #177.
